# Google App Engine configuration
runtime: python312

# Environment variables for production
env_variables:
  ENVIRONMENT: production
  DEBUG: false
  
  # Redis configuration (replace with your actual Redis instance details)
  REDIS_HOST: "your-redis-host.com"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "your-redis-password"
  REDIS_SSL: "true"
  
  # Bloom filter configuration
  BLOOM_EXPECTED_ITEMS: "10000000"
  BLOOM_FALSE_POSITIVE_RATE: "0.0001"
  BLOOM_REDIS_KEY: "bloom:passwords:prod"
  
  # API configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8080"
  
  # Security
  CORS_ORIGINS: '["https://yourdomain.com"]'

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2
