# Google Cloud Build configuration
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/bloom-filter-api:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/bloom-filter-api:latest',
      '.'
    ]
    dir: 'backend'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bloom-filter-api:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bloom-filter-api:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'bloom-filter-api',
      '--image', 'gcr.io/$PROJECT_ID/bloom-filter-api:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'ENVIRONMENT=production,DEBUG=false',
      '--set-env-vars', 'REDIS_HOST=${_REDIS_HOST},REDIS_PASSWORD=${_REDIS_PASSWORD}',
      '--set-env-vars', 'REDIS_SSL=true,BLOOM_REDIS_KEY=bloom:passwords:prod',
      '--memory', '512Mi',
      '--cpu', '1',
      '--concurrency', '100',
      '--max-instances', '10'
    ]

# Substitution variables (set these in Cloud Build trigger)
substitutions:
  _REDIS_HOST: 'your-redis-host.com'
  _REDIS_PASSWORD: 'your-redis-password'

options:
  logging: CLOUD_LOGGING_ONLY
